# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

set: ["e", "u", "pipefail"]
output: "prefixed"

run: once

vars:
  # aarch64 / x86_64
  PLATFORM:
    sh: uname -m
  # arm64 / amd64
  DPKG_ARCH:
    sh: dpkg --print-architecture
  # arm64 / x64
  ARCH:
    sh: |
      ARCH=
      dpkgArch="{{.DPKG_ARCH}}"
      case "${dpkgArch##*-}" in
        amd64) ARCH='x64' ;;
        arm64) ARCH='arm64' ;;
        *) echo "unsupported architecture"; exit 1 ;;
      esac
      echo -n $ARCH
  # arm64 / x86_64
  PLATFORM_ARCH:
    sh: |
      ARCH=
      dpkgArch="{{.DPKG_ARCH}}"
      case "${dpkgArch##*-}" in
        amd64) ARCH='x86_64' ;;
        arm64) ARCH='arm64' ;;
        *) echo "unsupported architecture"; exit 1 ;;
      esac
      echo -n $ARCH
  PKG: "./..."
  FAILFAST: "-failfast"
  TIMEOUT: "10m"
  RUN: ".*"
  TAGS: "-tags json1,netgo"
  BENCH_TIME: "30s"
  BENCH_RESULTS_DIR: "/tmp/benchmarks"
  BENCH_RESULTS_FILE: "/tmp/benchmarks/ledger.txt"
  BENCH_CPU_PROFILE: "/tmp/benchmarks/ledger.cpu.prof"
  BENCH_MEM_PROFILE: "/tmp/benchmarks/ledger.mem.prof"
  VERBOSE: "false"

includes:
  base:
    taskfile: /etc/Taskfile.yml
    dir: .
    flatten: true

tasks:
  prebuild:setup-go:
    internal: true
    status:
      - test -f /usr/local/go/bin/go
    cmd:
      task: sudo
      vars:
        NAME: "{{.TASK}}"
        CMD: |
          VERSION=1.26.6
          curl -L https://go.dev/dl/go${VERSION}.linux-{{.DPKG_ARCH}}.tar.gz | tar -xz -C /usr/local -f -
          sed -i '/export PATH/i\'$'\n''PATH=$PATH:/usr/local/go/bin' /etc/profile
          echo 'export PATH="$PATH:/usr/local/go/bin:/home/gitpod/go"' >> /home/gitpod/.profile


  setup:config:shpool:
    internal: true
    status:
      - test -f /home/gitpod/.config/shpool/config.toml
    cmd: |
      mkdir -p /home/gitpod/.config/shpool
      cat > /home/gitpod/.config/shpool/config.toml <<'EOF'
      initial_path = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:~/.local/bin:/usr/local/go/bin:~/go"
      [env]
      PSQL_EDITOR = "code -w"
      PGDATABASE = "ledger"
      PGPASSWORD = "ledger"
      PGPORT = "5432"
      EOF

  startup:install:
    internal: true
    deps:
      - prebuild:setup-go
    status:
      - test -f .task/signals/deps-install.done
    cmds:
      - go mod download
      - task: sync:done
        vars:
          SIGNAL: deps-install

  terminal:backend:
    deps: 
      - prebuild:setup-go
      - setup:config:shpool
    vars:
      ACTION: >-
        {{.ACTION | default "attach"}}
    requires:
      vars:
        - name: ACTION
          enum:
            - new
            - attach
    cmds:
      - task: terminal:{{.ACTION}}
        vars:
          NAME: backend
          DIR: >-
            {{.TASK_DIR}}
          CMD: clear && source ~/.profile && history -c

  pgweb:
    - docker compose up -d pgweb

  startup:
    deps:
      - prebuild:setup-go
      - postgres
      - pgweb
      - task: terminal:backend
        vars:
          ACTION: new

  default:
    cmds:
      - task: generate
      - task: lint
      - task: tests:local

  generate:
    cmds:
      - go generate {{.PKG}}

  lint:
    cmds:
      - golangci-lint run --fix {{if eq .VERBOSE "true"}}-v{{end}}

  tests:
    deps: [postgres]
    cmds:
      - >
        go test {{.TAGS}} {{if eq .VERBOSE "true"}}-v{{end}} -coverpkg {{.PKG}}
        -coverprofile coverage.out -covermode atomic {{.PKG}}
    env:
      NUMARY_STORAGE_DRIVER: "postgres"
      NUMARY_STORAGE_POSTGRES_CONN_STRING: "postgresql://ledger:ledger@127.0.0.1/ledger"

  tests:local:
    cmds:
      - task: tests:local:sqlite
      - task: tests:local:postgres

  tests:local:sqlite:
    cmds:
      - >
        go test {{.TAGS}} {{if eq .VERBOSE "true"}}-v{{end}} {{.FAILFAST}} -coverpkg {{.PKG}}
        -coverprofile coverage.out -covermode atomic
        -run={{.RUN}} -timeout {{.TIMEOUT}} {{.PKG}} |
        sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' |
        sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/'' |
        sed ''/RUN/s//$(printf "\033[34mRUN\033[0m")/''
      - task: print:coverage

  tests:local:postgres:
    deps: [postgres]
    cmds:
      - >
        go test {{.TAGS}} {{if eq .VERBOSE "true"}}-v{{end}} {{.FAILFAST}} -coverpkg {{.PKG}}
        -coverprofile coverage.out -covermode atomic
        -run={{.RUN}} -timeout {{.TIMEOUT}} {{.PKG}} |
        sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' |
        sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/'' |
        sed ''/RUN/s//$(printf "\033[34mRUN\033[0m")/''
      - task: print:coverage
    env:
      NUMARY_STORAGE_DRIVER: "postgres"
      NUMARY_STORAGE_POSTGRES_CONN_STRING: "postgresql://ledger:ledger@127.0.0.1/ledger"

  print:coverage:
    cmds:
      - go tool cover -html=coverage.out -o coverage.html
      - cov-report ./coverage.out
      - echo "To open the html coverage file, use one of the following commands:"
      - echo "open coverage.html on mac"
      - echo "xdg-open coverage.html on linux"
    silent: true

  bench:
    deps: [postgres]
    cmds:
      - mkdir -p {{.BENCH_RESULTS_DIR}}
      - >
        go test {{.TAGS}} {{if eq .VERBOSE "true"}}-v{{end}} {{.PKG}}
        -run=XXX -bench={{.RUN}} -benchmem -benchtime={{.BENCH_TIME}} -timeout {{.TIMEOUT}}
        -cpuprofile {{.BENCH_CPU_PROFILE}} -memprofile {{.BENCH_MEM_PROFILE}}
        | tee {{.BENCH_RESULTS_FILE}}
      - benchstat {{.BENCH_RESULTS_FILE}}
    env:
      NUMARY_STORAGE_DRIVER: "postgres"
      NUMARY_STORAGE_POSTGRES_CONN_STRING: "postgresql://ledger:ledger@127.0.0.1/ledger"

  bench:cpu:
    cmds:
      - go tool pprof -http=":" {{.BENCH_CPU_PROFILE}}

  bench:mem:
    cmds:
      - go tool pprof -http=":" {{.BENCH_MEM_PROFILE}}

  install:
    deps:
    - install:golangci-lint
    - install:perf

  install:golangci-lint:
    deps:
      - prebuild:setup-go
    cmds:
      - >
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
        sh -s -- -b /home/gitpod/go/bin latest
      - golangci-lint --version

  install:perf:
    deps:
      - prebuild:setup-go
    cmds:
      - /usr/local/go/bin/go install golang.org/x/perf/cmd/...@latest

  postgres:
    cmds:
      - docker compose up -d postgres

  clean:
    cmds:
      - go clean
      - rm -f {{.SERVICE}} coverage.out coverage.html
      - docker compose down -v

  sdk:template:
    desc: Extract templates
    dir: ./sdk
    preconditions:
      - sh: '[ "{{.CLI_ARGS}}" != "" ]'
        msg: Please specify generator as first cli arg (ie "task template -- go")
    cmds:
      - >
        docker run --rm -w /local -v ${PWD}:/local openapitools/openapi-generator-cli:v6.4.0 author
        template -g {{.CLI_ARGS}} -o templates/{{.CLI_ARGS}}

  sdk:generate:
    desc: Generate client code
    dir: ./sdk
    preconditions:
      - sh: '[ "{{.CLI_ARGS}}" != "" ]'
        msg: Please specify generator as first cli arg (ie "task generate -- go")
    cmds:
      - cp ../pkg/api/controllers/swagger.yaml swagger.yaml
      - sed -i -e "s/LEDGER_VERSION/{{.VERSION}}/g" swagger.yaml
      - >
        docker run --rm -w /local -v ${PWD}:/local openapitools/openapi-generator-cli:v6.4.0 generate
        -i ./swagger.yaml
        -g {{ (split "-" .CLI_ARGS)._0 }}
        -c ./configs/{{.CLI_ARGS}}.yaml
        -o ./sdks/{{.CLI_ARGS}}
        --git-user-id=formancehq
        --git-repo-id=numary-sdk-{{.CLI_ARGS}}
        -p packageVersion={{.VERSION}}

  sdk:test:
    desc: Test client code
    dir: ./sdk
    preconditions:
      - sh: '[ "{{.CLI_ARGS}}" != "" ]'
        msg: Please specify generator as first cli arg (ie "task test -- go")
      - sh: "[[ -e sdks/{{.CLI_ARGS}}/Taskfile.yml ]]"
        msg: "Not Taskfile found. You have to create a taskfile in ./sdks/{{.CLI_ARGS}}/ with a 'test' task"
    vars:
      RANDOM:
        sh: "echo $$"
    cmds:
      - |
        cd ./sdks/{{.CLI_ARGS}}
        task test

  goreleaser:test:pkg:
    desc: Test a package
    cmds:
      - docker run --platform linux/{{.Platform}} --rm --workdir /tmp -v $PWD/dist:/tmp {{.Image}} sh -c '{{.Cmd}} && goreleaser --version'

  goreleaser:test:rpm:
    desc: Tests rpm packages
    vars:
      rpm: "rpm --nodeps -ivh"
    cmds:
      - task: goreleaser:test:pkg
        vars:
          Platform: "amd64"
          Image: fedora
          Cmd: "{{.rpm}} numary_*_linux_amd64.rpm"
      - task: goreleaser:test:pkg
        vars:
          Platform: "arm64"
          Image: fedora
          Cmd: "{{.rpm}} numary_*_linux_arm64.rpm"

  goreleaser:test:deb:
    desc: Tests deb packages
    vars:
      dpkg: "dpkg --ignore-depends=git -i"
    cmds:
      - task: goreleaser:test:pkg
        vars:
          Platform: "amd64"
          Image: ubuntu
          Cmd: "{{.dpkg}} numary_*_linux_amd64.deb"
      - task: goreleaser:test:pkg
        vars:
          Platform: "arm64"
          Image: ubuntu
          Cmd: "{{.dpkg}} numary_*_linux_arm64.deb"

  run:
    cmds:
      - docker compose up -d --remove-orphans

  stop:
    cmds:
      - docker compose stop

  ps:
    cmds:
      - docker compose ps

  rm:
    deps: [stop]
    cmds:
      - docker compose rm -f
      - docker volume prune -f
      - rm -f {{.BENCH_CPU_PROFILE}} {{.BENCH_MEM_PROFILE}}
